---

roles:
  <project>/<project>-instance:
    description: "Instance role for the <project>"
    make_instance_profile: true

    allow_to_assume_me:
      - service: ec2

    allow_permission:
      - { action: "s3:Head*", resource: { s3: rca-project-artifacts-staging } }
      - { action: "s3:Get*", resource: { s3: rca-project-artifacts-staging } }
      - { action: "s3:List*", resource: { s3: rca-project-artifacts-staging } }
      - { action: "cloudwatch:PutMetricData", resource: "*" }
      - { action: "cloudformation:DescribeStackResource", resource: "*" }

      - { action: "iam:*", resource: { iam: __self__ } }

      - action: "sts:AssumeRole"
        resource:
          - { iam: "role/encryption/<project>-decryptor" }
